### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ghost** [RoanH/ManiaColumnCentering#1]
It's would be nice to see these in program :)
- [x] Ability to disable ColumnStart value backup
Also, this can be made by making backup in file but not lines, like "skin-backup-%date%-%time%.ini"
- [x] Add information about yourself in app with link to GitHub
Although this can be found by searching app tittle.

**Comment by RoanH** [comment]
Hey, thanks for the suggestions :)

I'll be adding a drop down where you can pick the backup strategy (or none).
And I'll be adding the links and version checking also found in my other programs.

If everything goes according to plan the new version should be released in 2-7 hours from now.

**Comment by RoanH** [comment]
I've implemented all the changes :D 

_If something was not implemented as expected feel free to reopen this issue!_
